export const jwtConstants = {
    secret: 'eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY5NTY3MzkxMCwiaWF0IjoxNjk1NjczOTEwfQ.iwPeXSdxrjyuyoYCgbzb6bz2mGZWvzK59nv-u95-xOo'
}